package.json
=> Upgrade to atom-space-pen-views 2.0.3

lib/error-matcher.js
=> Fix Issue #134

lib/build-view.js, lib/build.js, lib/error-matcher.js
Fixes #49 and adds clickable errors. This PR includes everything in PR #133.
=> Fix #49: Scroll build panel and clickable errors

README.md
Hello,
I updated the regex to match the full path.
Also I had to replace the ^ by \n to make it functional.
=> Updated error matching in README.md

README.md, lib/build.js, lib/error-matcher.js, spec/build-error-match-spec.js, spec/fixture/.atom-build.error-match-multiple-errorMatch.json
Allows to supply a list of regexes in errorMatch. See discussion in #131.
=> [Feature] Multiple regexes

lib/build-view.js, spec/build-spec.js, spec/build-view-spec.js, styles/build.less
Timer helps keep track of the time builds take.
It also gives a sense that stuff is happening.
=> BuildView: Include a timer

styles/build.less
=> BuildView: Transition outcome color

lib/tools/gulp-parser-task.js, spec/build-targets-spec.js
Maybe fixes #157.
Reverting changes from d3693f30e4310be898ed503fc8b14794b7b91739.
=> [Bugfix] Fix Gulp targets not showing up

lib/build-view.js, spec/build-view-spec.js, styles/build.less
There's no need for the ordered list anymore.
=> BuildView: Simplify panel

lib/build.js
=> If `cmd` or `cwd` is invalid. Let user know

lib/build-view.js
Fixes highlighting of some errors and maybe #201.
=> [Bugfix] Fixes links not showing up

README.md
Added APM Installs, APM Version, ApppVeyor Shield, Slack Badge.
Adjusted Travis and Gitter Badge.
=> Refine README Badges

lib/build.js
=> Only append /usr/local/bin on unix systems

lib/atom-build.js, package.json, spec/custom-provider-spec.js, spec/fixture/.atom-build.cson, spec/fixture/.atom-build.json
Also added specs for CSON files
=> Newer CSON-parser

lib/atom-build.js, lib/build.js, package.json, spec/custom-provider-spec.js, spec/fixture/.atom-build.yml
=> Support for yaml custom file

lib/build.js, lib/status-bar-view.js
This pull request replaces #260 .
=> Add status bar priority.

lib/build.js, lib/config.js
Hopefully I did this correctly.
I placed it at the end of the other checkbox config options and before the numbered/drop-down menu options. It seems like the most logical spot for it. 
Also tested and working, but you might want to branch it and make sure.
Fixes #291 (discussion)
=> New config option: "beepWhenDone". Makes a "beep" notification sound when the build is complete

lib/build-view.js, lib/build.js, spec/build-spec.js, styles/animations.less, styles/build.less
Modified the layout so that there is more space for
the actual build output and altered feedback for
errors, and building.
=> Layout: Less is more

lib/build.js, lib/status-bar-view.js
When building, a spinning gear will appear in the status
bar, so it is apparant that a build is in progress even if the
build window is closed.
=> Add spinning gear to status bar

lib/build-view.js
This way content can be searched while output is being appended.
=> Only scroll output if at the end

appveyor.yml, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-keymap-spec.js, spec/build-spec.js, spec/build-view-spec.js, spec/build-visible-spec.js, spec/fixture/.atom-build.error-match-multiple-errorMatch.json, spec/fixture/.atom-build.error-match-multiple-first.json, spec/fixture/.atom-build.error-match-multiple.json, spec/fixture/.atom-build.error-match-no-file.json, spec/fixture/.atom-build.error-match-no-line-col.json, spec/fixture/.atom-build.error-match.json
in preparation for running them on appveyor
=> Fixed specs when running on windows

README.md, lib/atom-build.js, lib/build.js, spec/build-atomCommandName-spec.js
This is #305 with added specs and README
=> Atom command name

lib/build-view.js, lib/config.js, spec/build-view-spec.js, spec/build-visible-spec.js, styles/build.less
This removes the percentage height. It can now be
set at any height directly.
Also modifies the terminal output so it always
adds show whole rows. I.e. size is rounded to
fit rows.
Fixes #312
=> Added a drag and resize of the build panel

lib/build-view.js
The max size of the build panel should be full
vertical size - tabs - other panels.
=> Do not allow build panel expand indefinitely.

lib/build-view.js
This also fixes the initial size of the terminal.
=> Resize terminal when font changes

lib/build-view.js, styles/build.less, styles/panel-top-bottom.less
Tested with Nucleus and Material and the build in themes.
=> Fixes for vendor themes

.travis.yml
Now tests on linux and osx and in chanels stable and beta.
=> Added travis test matrix

lib/build.js, lib/save-confirm-view.js, lib/target-manager.js, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-spec.js
Refactoring of target management.
Targets are handled by the TargetManager, this includes keeping track of them in its pathTarget, and whether a path is loading, the active target etc.
=> Target manager

lib/build-view.js, lib/config.js
=> Fix Increase terminal scrollback or allow configurable scrollback #414

lib/target-manager.js
It should always return a Promise.
Fixes #420
=> Consistent return value from target-manager.getTargets

lib/build.js, lib/status-bar-view.js, lib/target-manager.js, package.json, styles/build.less
Busy will show a nice spinning wheel and keep track of
the latest run tasks.
=> Let `busy` take care of running display

menus/build.json
This adds a few more of the commands to the package menu, and changes the label slightly on the existing two.
=> Add more menu actions

lib/utils.js, spec/utils-spec.js
=> Only replace string values

package.json, spec/.eslintrc, spec/build-atomCommandName-spec.js, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-hooks-spec.js, spec/build-keymap-spec.js, spec/build-spec.js, spec/build-targets-spec.js, spec/build-view-spec.js, spec/build-visible-spec.js, spec/custom-provider-spec.js, spec/linter-intergration-spec.js
Dispatching events seem to not work. Easier and is to check
via Atom's documented API which keymaps are registered and trust
that their stuff works - which we of course do for many other things
anyway.
=> Fixing keymap specs

lib/target-manager.js, spec/build-keymap-spec.js, spec/build-targets-spec.js
No more recursive loop when there are no targets
Thanks to @sphaerophoria for correctly identifying the issue
and providing an initial solution in #503.
Fixes: #484, #447
=> No recursive loop

spec/custom-provider-spec.js
See https://github.com/noseglid/atom-build/pull/497
=> Adds specs for .yaml file

lib/target-manager.js
=> Only register atomCommandName if it exists

lib/build-view.js
=> Reset user-select properly
