lib/build-view.js, lib/build.js
=> Remember panel height when creating it

lib/build.js
Use `cargo build` to build projects if `Cargo.toml` exists in the root
=> Add support for building Rust projects with Cargo

keymaps/build.json, lib/build.js, spec/build-spec.js, spec/fixture/.atom-build.error-match-multiple-first.json, spec/fixture/.atom-build.error-match-multiple.json
Instead of only allowing to jump to the first location found by the given errorMatch regular expression, you can cycle through every error with build:error-match. At the end it loops around to the beginning.
build:error-match-first (cmd-alt-h) jumps directly back to the beginning.
=> Cycling through match errors

keymaps/build.json, lib/build-view.js, lib/build.js, spec/build-spec.js, spec/build-visible-spec.js
This command allows you to show or hide the build view. The default shortcut is `cmd-alt-b cmd-alt-v` (Mac) or `ctrl-alt-b ctrl-alt-v` (others).
=> Add build:toggle-view command

lib/error-matcher.js
A simple change, which makes working with multiple panes and atom-build easier. Before this patch I would end up with multiple files opened in all panes.
=> Search all panes when opening a matched file

lib/build-view.js, spec/build-spec.js, spec/build-visible-spec.js
fix for #108 
I think the idea behind the option "Keep visibile" would be to keep the build output visible after a build, not to have the build output panel visible at all times. Package activation happens each time a new atom window is opened and it doesn't seem useful to me to have the build panel open right away (with no output).
I could be wrong though, and perhaps another option is needed. In any case, this PR changes the behaviour to keep the panel visible after a successful build, but not immediately after package activation.
=> don't attach view on package activation

lib/tools/gulp.js
Enable the use of babel configuration for Gulp.
=> Enable the use of babel configuration for Gulp.

lib/build.js
This problem was exposed since I'm using [tree-view-git-projects](https://github.com/JavascriptIsMagic/tree-view-git-projects), and it re-sorts projects. This should also help in other cases when users have multiple root folders.
=> Only use project path if it contains active file

lib/build.js, package.json
It ended up being pretty easy to use a Service-based architecture, and I had some free time, so I did this.  :smile:
See https://github.com/bwinton/atom-build-jpm or https://github.com/bwinton/atom-build-markdown for example service providers.
=> Use a service instead of hard-coding all the tools.

lib/build-view.js
Some programs in windows only use \n as newline, e. g. coffee. Without this fix, the output of such a program is only displayed, when it has finished running. Since both \r\n and \n end with \n, this fix should not cause problems.
=> [Bugfix] Not all windows programs use \r\n as line ending

lib/build-view.js, lib/error-matcher.js
This PR fixes two bugs:
- Errors are now highlighted, when the build is finished, not when the user goes to the first error
- no error matching is performed, when no errorMatcher is set
=> [Bugfix] Parse on errorMatcher.set / handle no errorMatcher correctly

lib/build-view.js, spec/build-view-spec.js
Code like the following could cause additional linebreaks in the build-window:
```coffeescript
process.stdout.write("same line\nsame");
setTimeout (-> process.stdout.write("line\n")), 1000
```
This PR fixes this bug, by removing the buffer and simply appending to the first `li` in the output instead of adding new `li`.
=> [Bugfix] Don't insert additional newlines

keymaps/build.json
On Linux, editor:move-to-previous-subword-boundary is bound
to `ctrl-alt-b`. Add specificity to the build keymap to win.
Fixes #168
=> Keymap specificity to not collide

.jscsrc, lib/error-matcher.js
Avoid enumerating potential extended properties on
the array prototype.
Fixes #173
=> ErrorMatcher: Defensive array loops

.jscsrc, lib/build-view.js, lib/build.js, lib/error-matcher.js, package.json, spec/build-error-match-spec.js, spec/build-view-spec.js, styles/build.less
The interfaces between `build`, `error-matcher` and `build-view`
is improved to decouple the modules. `error-matcher` no longer
have any knowledge of how the matching it performs is actually
used, and `build-view` no longer knows what the links it creates
are used for.
All together: better design.
=> Build view interface

README.md
The JSON wasn't valid in the example target due to a missing comma.
=> Fix example target JSON

lib/tools/Cargo.js, lib/tools/Elixir.js, lib/tools/Grunt.js, lib/tools/gulp.js, lib/tools/make.js, lib/tools/npm_apm.js
Bundled tools will be removed in v0.48.0. As a preparation,
in v0.47.0 a warning will be included which urges the user
to install the stand-alone package. The warning will only
be shown once, and only if the tool is being used.
=> Added Warning about bundled tools removal

lib/build-view.js, lib/build.js, spec/build-error-match-spec.js, spec/build-view-spec.js, styles/build.less
Configuration where to attach the build panel.
=> Panel orientation

README.md, lib/build.js
Help re-use of any information that might be retrieved
in `isEligable` once `settings` is called.
=> Build: providers get called with context

lib/build.js, spec/build-confirm-spec.js
Make sure dialog exists before calling commands
on it.
Fixes #202
=> Calling dialog commands without dialog

lib/error-matcher.js, spec/build-error-match-spec.js
`cwd` should only be prepended once, not once for every
error match issued.
Fixes #194
=> ErrorMatcher: Do not prepend cwd multiple times

lib/build-view.js, styles/build.less
I think the output view looks a lot better when it uses the font set for the editor, instead of simply going with whatever the user agent default is for `monospace`. This updates the stylesheet to default to the same default fonts as the core stylesheet of Atom, and uses the configured font by creating an inline style on the output element.
=> better default font and match editor font

README.md, keymaps/build.json
Currently the default key bindings on Linux and Windows aren't optimal. For example `ctrl-alt-t` is already used by most distros to open a terminal, see #163. In general it's uncommon for Linux apps to use `ctrl-alt-*` keybindings as they are usually used by system apps.
After looking through the issues, it looks to me that only people on Linux/Windows have problems with the default keybindings: #168, #198.
Also note that `ctrl-alt-*` has some problems on Windows, see this post which advises not to use them on Windows at all: https://github.com/atom/atom-keymap/issues/35#issuecomment-117284074
Last but not least they are rather uncommon among existing build apps like Sublime Text or CodeBlocks.
I've tried to find some new defaults, here is my reasoning for them:
* `f4` error-match: This …
=> Improve default keybindings for Linux/Windows

lib/build.js
As far as I understand javascript's "replace" with string arguments does only single replacement. I needed to replace all matches when building some of the Go projects. The use case was to redefine an environment variable like so: `"GOPATH": "{PROJECT_PATH}:{PROJECT_PATH}/vendor"`. With this fix it actually works.
=> Use regexps with '/g' modifier to replace all matches of built-in vars.

styles/build.less
Some css tweaks:
- use `@component-padding` from ui-theme for padding instead of `10px`
- set minimum width
- all buttons in a row so output gets to use the entire width of the panel
Before  
After
=> improve layout in sidebar mode

lib/atom-build.js, lib/build.js, package.json, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-keymap-spec.js, spec/build-spec.js, spec/build-targets-spec.js, spec/build-view-spec.js, spec/build-visible-spec.js
Targets (as well as active target) are now cached on a
per project basis. This has several implications:
* Targets will only be reloaded when root project paths
are added/removed or when triggered manually. This means
that selecting active target wont implicitly refresh the
cache. This improves usability when switching between active
targets.
* Working with multiple project roots is now possible without
re-selecting active targets.
Fixes #179
=> Better support for multiple root projects

lib/error-matcher.js
`package.json` uses `xregexp` as package name, but you use `XRegExp` in your project. Fixed in this file.
=> Fixed dependency.

lib/build.js
This PR addresses #224. It adds a new option to allow disabling the behavior added in #144. The default value does not change the current behavior.
I added the new option `matchedErrorFailsBuild` after the build trigger options and before the option determining the behavior after the build (scrollOnError).
=> add option to toggle if build should fail if error regex matches

lib/build.js
Showing the path so it is easier to debug
issues where command is not found.
=> When build failed, show the path

lib/build.js
They will now reach the same specificity as the built
in commands. Since they are applied later they will
take precedence. Thus allowing custom keymaps to override
built in keymaps.
=> Update specificity of custom keymaps

spec/build-keymap-spec.js
If the build is slow, and/or build package closes the build
panel due to its timeout, the toggle panel will really open
the panel - causing the testcase to fail. Defer to always letting
the panel be auto-closed and just wait for it to be closed.
=> Fix blinking keymap testcase

lib/build.js
Fields of `process.env` could be `undefined` in some environment (for example, mine):
This will cause the following error:
It can be fixed by simply initializing `replace`'s `value` parameter with empty string by default.
=> Initialize undefined environment variable properly

lib/build.js, spec/build-spec.js
Also updated test which tested for this condititon,
however - the bug only occured after targets where
refreshed, which they didn't have time for in the
test.
Fixes #269
=> Do not throw an error if build config is missing

lib/build.js
(partly) because arguments might still depend on the platform (windows path separators). Since this is less an issue with node processes, this enhancement can still be valuable.
=> (partly) cross-platform build specs via cmd (sh:true) for windows

lib/build.js, lib/config.js, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-keymap-spec.js, spec/build-spec.js, spec/build-targets-spec.js, spec/build-view-spec.js, spec/build-visible-spec.js
The refreshed targets notifications can be quite intrusive.
Provide an option for disabling them.
Fixes #284
=> Option to hide notifications

lib/build.js
If the targets list has been open, it is now required to
re-open it once the targets-loading has finished.
This fixes that so items are added to the existing list.
=> Fill an open target list once loaded

lib/build.js
Some tools may not have `removeAllListeners` method, especially those
which do not extend `EventEmitter`.
Deactivating this package (Settings > Packages > build > Deactivate) leads to the following error: 
```
Error deactivating package 'build' TypeError: tool.removeAllListeners is not a function
at /path/to/atom-build/lib/build.js:98:12
...
```
=> Check if tool.removeAllListeners esists before call

lib/build.js, lib/status-bar-view.js
This stops the spinning gear, and sets the fire icon.
=> When build is aborted, update status-bar-view

lib/build.js, package.json
This became a much deeper issue than I had first realized! https://github.com/nodejs/node-v0.x-archive/issues/2318 has a lot of information related to the problem I was having.
Specifically, my home folder on Windows has a space in it. FILE_ACTIVE would provide the full path to the file I was building. But node's escaping isn't ideal when it tries to pass that to the Windows cmd executable.
Based on the numerous references to cross-spawn in the issue above, I ended up implementing this by using cross-spawn but only when sh is false. Using it when sh is true broke a ton of use cases in the spec and I'm sure out in the wild that were implemented like this:
`{
"cmd": "echo Hello World!",
"sh": true
}`
=> Use cross-spawn when sh is false for better Windows spawning support

lib/atom-build.js, spec/build-atomCommandName-spec.js, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-keymap-spec.js, spec/build-spec.js, spec/build-targets-spec.js, spec/build-view-spec.js, spec/build-visible-spec.js, spec/custom-provider-spec.js
As discussed on https://github.com/noseglid/atom-build/issues/209
Adding the possibility to use global config files, as a first step, to use the user's home directory looking for any of the supported config file types.
as a bug: the plugin can't watch the whole directory structure, if an atom build file is added to the home directory after the project is loaded, atom build won't recognize the new file, the project needs to be reloaded.
This commit may looks big but tests required lots of modification to support the new "isElegible" method fallback to use user home directory.
=> Add posibility to use an atom-build config file from the user's home

lib/build-view.js, lib/build.js, lib/error-matcher.js, package.json, spec/build-atomCommandName-spec.js, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-keymap-spec.js, spec/build-spec.js, spec/build-targets-spec.js, spec/build-view-spec.js, spec/build-visible-spec.js, spec/custom-provider-spec.js, spec/fixture/.atom-build.error-match-long-output.json, spec/fixture/.atom-build.error-match-multiple-errorMatch.json, spec/fixture/.atom-build.error-match-multiple-first.json, spec/fixture/.atom-build.error-match-multiple.json, styles/animations.less, styles/build.less
Term.JS is very capable of displaying output targeted
at terminals in HTML. It supports a wide range of control
characters making output display correctly. Advanced stuff
such as full screen renderings work.
There are two caveats with this implementation:
* No longer underline and make links clickable when
error matched. The short key still works, and it
still scrolls the terminal to the correct location.
* Since term.js hard break lines when terminal width
is reached (regardless of occurance of newline char)
it is difficult to find a matched text. The current
implementation decreases the matched text until it
finds a subset that matches. This may of course not
be accurate at all times. But hopefully close enough.
I think the two caveats are minor considering the reduced
maintenance of …
=> Use Term.JS rather than custom output

lib/build-view.js
When a build has completed, only reset the focus
if we still "own" the focus, i.e. no other focus
choices has been made by the user.
Fixes #300
=> Only re-focus if we still "own" focus

lib/build.js
If the project folder for some reason can not
be derive `realpath`, skip that folder and continue
with other potential candidates.
Fixes #273
Fixes #322
=> Handle if project folder has gone away

lib/build.js, spec/build-hooks-spec.js, spec/fixture/.atom-build.hooks.json, spec/fixture/atom-build-hooks-dummy-package/main.js, spec/fixture/atom-build-hooks-dummy-package/package.json
If target has the "preBuild" attribute and it is a function, it will be called
before the build. If "preBuild" returns a promise, build will be started after
the promise resolution.
"postBuild" hook is called upon child closed. "postBuild" receives a build
status as an argument.
Such feature is necessary for platformio/platformio-atom-ide/issues/45.
=> Implement pre-/post-build hooks

lib/atom-build.js, lib/build.js, lib/google-analytics.js, package.json, spec/build-confirm-spec.js, spec/build-targets-spec.js
With the entry of ES6, and the possibility to use
babel to transpile both ES6 and ES7 to ES5 compatible
javascript, there really is no need for utility library lodash.
Removing it speeds up load times for build.
=> Removed lodash dependency

lib/build-view.js, lib/config.js, styles/build.less
Terminal works "best" under black background and white
text. However this may not look very good with light theme,
or other dark themes. Allow user to opt out of overriden
colors.
Fixes #338
=> Optionally override theme with terminal style

README.md, lib/build.js, lib/error-matcher.js, package.json, spec/build-spec.js, spec/build-view-spec.js, spec/fixture/.atom-build.error-match-multiple.json, spec/fixture/.atom-build.error-match.message.json, spec/fixture/atom-build-spec-linter/atom-build-spec-linter.js, spec/fixture/atom-build-spec-linter/package.json, spec/helpers.js, spec/linter-intergration-spec.js
This gives a nice overview of all build errors.
Tasks left before this is mergable
- ~~[ ] scroll the build output to the matched error~~: There doesn't seem to be any support in the linter for this. Issue created: https://github.com/steelbrain/linter/issues/1106. Will fix that in a separate PR )
Fixes #346
=> Integrate Atom Linter

lib/build-view.js, lib/config.js, spec/build-view-spec.js, styles/panel-top-bottom.less
If content is not of interest, this gives more space to what
the user might deem important.
Also changed so `resizer` element is used in the bottom position too.
Fixes #357
=> Option to hide panel heading

lib/build.js
Only `file` is required by the errorMatcher API.
The linter integration should therefore report
the first row or the first column if the value is missing.
This will place the corsor "as correct as possible".
Fixes #364
=> Linter report no row or col

README.md, lib/atom-build.js, lib/build.js, spec/custom-provider-spec.js, spec/fixture/.atom-build.js
Support for defining `.atom-build.js`.
This format support functions so that `preBuild` and `postBuild` can be defined.
The configuration must be `module.exports`'d.
Need
Fixes #362
=> Support for `.atom-build.js`

lib/build.js
Fix execution of commands on Windows which contain `/`.
Try the following `.atom-build.yml` on Windows:
```
cmd: explorer https://github.com/noseglid/atom-build
```
Expected result: Opens the correct URL in the browser.
Actual result: Tries to open `https:\github.com\noseglid\atom-build`.
=> Don't normalize cmd

README.md, lib/build.js, spec/linter-intergration-spec.js
previously the lints did not show up in files if the paths were relative. Alternatively this could be changed in atom-linter directly, but I don't think that's feasible as atom-linter doesn't know about projects, but atom-build explicitly does.
fixes #359
=> support relative paths in linter + spans that span multiple characters/lines

lib/atom-build.js, spec/build-spec.js, spec/build-visible-spec.js
On linux, watch can not be used since closing the watcher triggers
a callback in the new watcher which ends up being an infinite loop.
Fixes #277
=> Use watchFile on Linux

lib/build.js, lib/config.js
Hi,
I need this for a build provider which depends on the currently selected file.
This is due to the fact, that I usually don't add each (latex) project path to atom, but one path with subprojects.
If this gets merged, I could also publish my small provider.
=> added option to refresh targets on demand

package.json
If git is not installed in the system (and it is OK), user will receive
```
Installing “build@0.59.0” failed.Hide output…
Failed to install build because Git was not found.
The build package has module dependencies that cannot be installed without Git.
You need to install Git and add it to your path environment variable in order to install this package.
You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com
Run apm -v after installing Git to see what version has been detected.
```
Please release 0.59.1. Thanks.
=> Allow to install package without GIT

lib/target-manager.js, spec/build-confirm-spec.js, spec/build-error-match-spec.js, spec/build-keymap-spec.js, spec/build-spec.js, spec/build-targets-spec.js, spec/build-view-spec.js, spec/build-visible-spec.js, spec/linter-intergration-spec.js
This helps resolve the issue where someone installs
atom-build, creates a yml file and manually have to
hit refresh to get the targets in there.
Fixes #409
=> Refresh the target list when without targets

lib/build.js, spec/build-error-match-spec.js
Allow error matching even if build is aborted. This can be useful
if you spot an error in the output, and the build is long running.
Really, there's no drawback to allowing it, so...
Fixes #382
=> Error match on abort

lib/target-manager.js, spec/build-spec.js, spec/build-targets-spec.js
If selecting targets when a file which is not part of an open
project in Atom is open, it should gracefully let the user know
that this is the case via a notification.
Fixes #403
=> Avoid exception when selecting targets outside of project

lib/build-view.js
Resizer is always available. The panel heading as reference
was just legacy from before when the resizer didn't exist
in bottom mode.
Fixes #379
=> Use resizer when calculatin resize

styles/build.less
The 600 weight is fine for the panel header, but the output is much easier to read if it's at normal font-wight.
=> normal font-weight in build output "terminal"

README.md, lib/atom-build.js, lib/build-view.js, lib/build.js, lib/error-matcher.js, lib/linter-integration.js, spec/build-error-match-spec.js, spec/fixture/.atom-build.error-match-function.js, spec/fixture/.atom-build.error-match-no-exit1.json, spec/fixture/.atom-build.match-function-change-dirs.js, spec/fixture/.atom-build.match-function-trace.js, spec/fixture/.atom-build.match-function-warning.js, spec/fixture/.atom-build.warning-match.json, spec/fixture/change_dir_output.txt, spec/linter-intergration-spec.js
This adds `warningMatch` and improves `functionMatch` to allow build providers to emit almost any kind of lint that is specified here: https://github.com/steelbrain/linter/wiki/Linter-API#messages
An example of a modified `build-cargo`:
fixes #408
=> enable traces (sub/child-errors) and custom "error types"

lib/google-analytics.js, package.json
It's easy enough to generate a "good enough" unique id.
No need to pull in a dependency for it.
=> Remove UUID dependency

lib/target-manager.js
There are several spots in the `TargetManager` that spit out Atom notifications for errors, that contain stack traces. These stack traces can be shown in the notification with the `stack` option, rather than appending them to the details. The notification will show a pretty little toggle-able stack trace.
See atom/notifications#126. It's most likely safe to use this option, since it's just a property containing a string - and that's probably not likely to change in the future.
=> Make use of notification stack option in TargetManager

lib/target-manager.js
This simply adds the name of the build provider to the notification when an error occurs while getting the build settings.
=> Make error notification more descriptive

create-provider.md, lib/build.js
This adds the capability for a single package to provide multiple build providers.
=> Allow consumeBuilder to accept arrays

README.md, lib/atom-build.js, lib/build-view.js, lib/build.js, spec/build-error-match-spec.js, spec/build-spec.js, spec/linter-intergration-spec.js, styles/build.less
While SIGTERM may be the "correct" choice from a documentation
standpoint, SIGINT is more widely used. Most applications are
designed to run in a terminal and most (all?) send SIGINT
when issuing ^C.
This PR simulates this behavior from atom-build.
=> Send SIGINT rather than SIGTERM

README.md, lib/linter-integration.js, spec/fixture/.atom-build.match-function-html.js, spec/fixture/.atom-build.match-function-message-and-html.js, spec/fixture/.atom-build.match-function-trace-html.js, spec/fixture/.atom-build.match-function-trace-message-and-html.js, spec/linter-intergration-spec.js
Added support for the Linter's message `html` field via `html_message`.
fixes #428
=> Linter's html field support

lib/targets-view.js
Add `build-target` to class list of the build target list view, to distinguish it from other modals for styling purposes.
=> Add class to build target modal

README.md, lib/build.js
=> added: postBuild is now also passed stdout and stderr, allowing custom handling of build output

lib/build.js, package.json
[cross-spawn-async has been deprecated](https://github.com/IndigoUnited/node-cross-spawn-async#cross-spawn-async)
=> Replace cross-spawn-async with cross-spawn

spec/build-hooks-spec.js, spec/fixture/atom-build-hooks-dummy-package/main.js
I searched through several build providers to see if this would break anything, and I haven't yet found any uses of this hook, but this needs more extensive searching to be sure.
=> Fix spelling: succeding -> succeeding

lib/utils.js
Atom >= 1.13 doesn't return a real path for `textEditor.getPath()`. In this case, affected projects will not be available for "build".
For example, project is located in `/private/tmp/myproject`
* `fs.realpathSync('/private/tmp/myproject') === '/private/tmp/myproject'`
* `textEditor.getPath() === '/tmp/myproject'`
* `fs.realpathSync(textEditor.getPath()) === '/private/tmp/myproject'`
=> Fix issue with incorrect path for text editor

lib/build.js, lib/target-manager.js, package.json
Busy Signal is most widely adopted and it doesn't make sense
to have 2 packages which does the same thing. Get with the program
and use `busy-signal`.
Fixes #528
=> Use `busy-signal` over `busy`

lib/build.js
If we don't close stdin, subprocesses that would ask for user input
block forever. Since atom-build has no way to interact with the spawned
subprocesses, just close it to have them fail.
=> close stdin in spawned child processes
